2018-07-18 14:55:31.210 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 14:55:31.210 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 14:55:31.363 +05:30 [Information] Request finished in 161.3002ms 200 
2018-07-18 14:55:32.102 +05:30 [Information] Request finished in 927.5319ms 404 
2018-07-18 14:55:46.512 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger  
2018-07-18 14:55:46.519 +05:30 [Information] Request finished in 7.7928ms 301 
2018-07-18 14:55:46.524 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 14:55:46.548 +05:30 [Information] Request finished in 22.0149ms 200 text/html
2018-07-18 14:55:46.578 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 14:55:46.580 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 14:55:46.587 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 14:55:46.639 +05:30 [Information] Sending file. Request path: '"/swagger-ui.css"'. Physical path: '"N/A"'
2018-07-18 14:55:46.639 +05:30 [Information] Sending file. Request path: '"/swagger-ui-bundle.js"'. Physical path: '"N/A"'
2018-07-18 14:55:46.642 +05:30 [Information] Sending file. Request path: '"/swagger-ui-standalone-preset.js"'. Physical path: '"N/A"'
2018-07-18 14:55:46.735 +05:30 [Information] Request finished in 153.9971ms 200 text/css
2018-07-18 14:55:46.742 +05:30 [Information] Request finished in 152.0912ms 200 application/javascript
2018-07-18 14:55:46.821 +05:30 [Information] Request finished in 248.5514ms 200 application/javascript
2018-07-18 14:55:47.248 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 14:55:47.281 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/favicon-32x32.png  
2018-07-18 14:55:47.284 +05:30 [Information] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"'
2018-07-18 14:55:47.288 +05:30 [Information] Request finished in 7.4024ms 200 image/png
2018-07-18 14:55:47.295 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/favicon-16x16.png  
2018-07-18 14:55:47.299 +05:30 [Information] Sending file. Request path: '"/favicon-16x16.png"'. Physical path: '"N/A"'
2018-07-18 14:55:47.302 +05:30 [Information] Request finished in 7.2571ms 200 image/png
2018-07-18 14:55:47.476 +05:30 [Information] Request finished in 228.0639ms 200 application/json
2018-07-18 15:54:16.119 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 15:54:16.388 +05:30 [Information] Request finished in 278.3992ms 404 
2018-07-18 16:09:55.875 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:09:55.875 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:09:55.967 +05:30 [Information] Request finished in 152.2894ms 200 
2018-07-18 16:09:56.323 +05:30 [Information] Request finished in 495.3244ms 404 
2018-07-18 16:09:56.878 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:09:56.903 +05:30 [Information] Request finished in 25.1555ms 200 text/html
2018-07-18 16:09:56.925 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:09:56.933 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:09:56.963 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:09:57.009 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:09:57.010 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:09:57.013 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:09:57.039 +05:30 [Information] Request finished in 75.3591ms 304 application/javascript
2018-07-18 16:09:57.047 +05:30 [Information] Request finished in 98.472ms 304 text/css
2018-07-18 16:09:57.049 +05:30 [Information] Request finished in 87.6104ms 304 application/javascript
2018-07-18 16:09:57.423 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:09:57.635 +05:30 [Information] Request finished in 210.5321ms 200 application/json
2018-07-18 16:10:25.016 +05:30 [Information] Request starting HTTP/1.1 POST http://localhost:55306/api/device?DeviceIdentifier=12345&UserName=sheikhimran  0
2018-07-18 16:10:25.195 +05:30 [Information] Executing action method "OnSolve.Mobile.Web.Controllers.DeviceVerificationController.Post (OnSolve.Mobile.Web)" with arguments (["OnSolve.Mobile.Web.Models.VerifyDeviceRequest"]) - ModelState is Valid
2018-07-18 16:10:30.359 +05:30 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-07-18 16:10:30.386 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.DeviceVerificationController.Post (OnSolve.Mobile.Web)" in 5264.2139ms
2018-07-18 16:10:30.390 +05:30 [Information] Request finished in 5374.105ms 200 application/json; charset=utf-8
2018-07-18 16:12:05.974 +05:30 [Information] Request starting HTTP/1.1 POST http://localhost:55306/api/device/SlJ1T2BjZ05bVlFgenphMWFfMkckRV9sMHF0cHVLSHEqJHN8aTNLUnRMVV59QTBqKFRmUmBgSjRXOE5KWVtqbQ==/token/12345  0
2018-07-18 16:12:06.000 +05:30 [Information] Executing action method "OnSolve.Mobile.Web.Controllers.DeviceVerificationController.Post (OnSolve.Mobile.Web)" with arguments (["SlJ1T2BjZ05bVlFgenphMWFfMkckRV9sMHF0cHVLSHEqJHN8aTNLUnRMVV59QTBqKFRmUmBgSjRXOE5KWVtqbQ==", "12345"]) - ModelState is Valid
2018-07-18 16:12:06.080 +05:30 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-07-18 16:12:06.084 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.DeviceVerificationController.Post (OnSolve.Mobile.Web)" in 85.2999ms
2018-07-18 16:12:06.086 +05:30 [Information] Request finished in 115.3216ms 200 application/json; charset=utf-8
2018-07-18 16:13:01.747 +05:30 [Information] Request starting HTTP/1.1 POST http://localhost:55306/api/user/sheikhimran/jwt application/json-patch+json 30
2018-07-18 16:13:02.876 +05:30 [Information] Executing action method "OnSolve.Mobile.Web.Controllers.JwtController.Post (OnSolve.Mobile.Web)" with arguments (["sheikhimran", "ZHE1TTdkWTZwcWNmWjFtRXE5QlB2QHZeaW5mYXUwXkNyeFZOdnNjUGA4cktZdGtWIThqT3VKQG5gYnVZfE5RcA==", "OnSolve.Mobile.Web.Models.PasswordModel"]) - ModelState is Valid
2018-07-18 16:13:06.220 +05:30 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
2018-07-18 16:13:06.225 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.JwtController.Post (OnSolve.Mobile.Web)" in 4469.3895ms
2018-07-18 16:13:06.234 +05:30 [Information] Request finished in 4485.7341ms 200 application/json; charset=utf-8
2018-07-18 16:14:00.101 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage/id?messageId=1  
2018-07-18 16:14:00.197 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 89.3857ms
2018-07-18 16:14:00.228 +05:30 [Error] Connection id ""0HLFCJB6KR903"", Request id ""0HLFCJB6KR903:00000003"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:14:00.233 +05:30 [Information] Request finished in 135.085ms 500 
2018-07-18 16:14:59.647 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage/id?messageId=1  
2018-07-18 16:15:06.468 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 6818.0107ms
2018-07-18 16:15:06.477 +05:30 [Error] Connection id ""0HLFCJB6KR903"", Request id ""0HLFCJB6KR903:00000004"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:15:06.482 +05:30 [Information] Request finished in 6839.7913ms 500 
2018-07-18 16:15:56.906 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage/id?messageId=1  
2018-07-18 16:15:58.715 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 1786.2866ms
2018-07-18 16:15:58.720 +05:30 [Error] Connection id ""0HLFCJB6KR903"", Request id ""0HLFCJB6KR903:00000005"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:15:58.744 +05:30 [Information] Request finished in 1818.823ms 500 
2018-07-18 16:16:21.275 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:16:21.280 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:16:21.368 +05:30 [Information] Request finished in 146.1335ms 200 
2018-07-18 16:16:21.664 +05:30 [Information] Request finished in 449.5231ms 404 
2018-07-18 16:16:25.622 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:16:25.649 +05:30 [Information] Request finished in 27.0431ms 200 text/html
2018-07-18 16:16:25.674 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:16:25.678 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:16:25.684 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:16:25.759 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:16:25.760 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:16:25.786 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:16:25.807 +05:30 [Information] Request finished in 102.082ms 304 text/css
2018-07-18 16:16:25.815 +05:30 [Information] Request finished in 117.038ms 304 application/javascript
2018-07-18 16:16:25.824 +05:30 [Information] Request finished in 120.8651ms 304 application/javascript
2018-07-18 16:16:25.936 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:16:26.147 +05:30 [Information] Request finished in 210.7736ms 200 application/json
2018-07-18 16:16:50.864 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:16:53.399 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 2437.4203ms
2018-07-18 16:16:53.432 +05:30 [Error] Connection id ""0HLFCJEPGJFLH"", Request id ""0HLFCJEPGJFLH:00000002"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:16:53.437 +05:30 [Information] Request finished in 2571.1978ms 500 
2018-07-18 16:17:51.204 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:17:51.204 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:17:51.294 +05:30 [Information] Request finished in 152.9915ms 200 
2018-07-18 16:17:51.623 +05:30 [Information] Request finished in 467.4155ms 404 
2018-07-18 16:17:54.208 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:17:54.268 +05:30 [Information] Request finished in 45.3498ms 200 text/html
2018-07-18 16:17:54.299 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:17:54.301 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:17:54.303 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:17:54.330 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:17:54.355 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:17:54.378 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:17:54.402 +05:30 [Information] Request finished in 87.1783ms 304 application/javascript
2018-07-18 16:17:54.404 +05:30 [Information] Request finished in 102.0226ms 304 application/javascript
2018-07-18 16:17:54.405 +05:30 [Information] Request finished in 125.7463ms 304 text/css
2018-07-18 16:17:54.542 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:17:54.741 +05:30 [Information] Request finished in 197.4707ms 200 application/json
2018-07-18 16:18:03.748 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:18:03.921 +05:30 [Information] Executing action method "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" with arguments (["1"]) - ModelState is Valid
2018-07-18 16:18:10.771 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 6926.8049ms
2018-07-18 16:18:10.803 +05:30 [Error] Connection id ""0HLFCJFK9TCK6"", Request id ""0HLFCJFK9TCK6:00000002"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Int64.Parse(String s)
   at OnSolve.Mobile.Web.Controllers.TextMessageController.<Get>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:18:10.807 +05:30 [Information] Request finished in 7058.9216ms 500 
2018-07-18 16:18:43.784 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:18:43.784 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:18:43.784 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:18:43.881 +05:30 [Information] Request finished in 158.9103ms 200 
2018-07-18 16:18:43.914 +05:30 [Information] Request finished in 195.4071ms 200 text/html
2018-07-18 16:18:43.974 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:18:43.975 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:18:43.981 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:18:44.056 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:18:44.057 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:18:44.059 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:18:44.085 +05:30 [Information] Request finished in 124.3221ms 304 text/css
2018-07-18 16:18:44.090 +05:30 [Information] Request finished in 92.2967ms 304 application/javascript
2018-07-18 16:18:44.101 +05:30 [Information] Request finished in 127.6955ms 304 application/javascript
2018-07-18 16:18:44.274 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:18:44.366 +05:30 [Information] Request finished in 649.7931ms 404 
2018-07-18 16:18:44.480 +05:30 [Information] Request finished in 204.1073ms 200 application/json
2018-07-18 16:19:09.393 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:19:26.768 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 17276.6386ms
2018-07-18 16:19:26.806 +05:30 [Error] Connection id ""0HLFCJG3VGKPD"", Request id ""0HLFCJG3VGKPD:00000003"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:19:26.810 +05:30 [Information] Request finished in 17418.9996ms 500 
2018-07-18 16:20:42.192 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:20:53.059 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 10862.1357ms
2018-07-18 16:20:53.064 +05:30 [Error] Connection id ""0HLFCJG3VGKPH"", Request id ""0HLFCJG3VGKPH:00000001"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:20:53.067 +05:30 [Information] Request finished in 10876.4026ms 500 
2018-07-18 16:34:18.721 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:35:29.826 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:35:29.826 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:35:29.928 +05:30 [Information] Request finished in 162.8189ms 200 
2018-07-18 16:35:30.249 +05:30 [Information] Request finished in 489.6541ms 404 
2018-07-18 16:35:49.257 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:35:49.289 +05:30 [Information] Request finished in 33.0143ms 200 text/html
2018-07-18 16:35:49.306 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:35:49.310 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:35:49.338 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:35:49.362 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:35:49.387 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:35:49.388 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:35:49.415 +05:30 [Information] Request finished in 85.5278ms 304 application/javascript
2018-07-18 16:35:49.418 +05:30 [Information] Request finished in 89.1626ms 304 text/css
2018-07-18 16:35:49.427 +05:30 [Information] Request finished in 73.6762ms 304 application/javascript
2018-07-18 16:35:50.250 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:35:50.443 +05:30 [Information] Request finished in 192.8206ms 200 application/json
2018-07-18 16:41:19.531 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:41:23.394 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 3759.2138ms
2018-07-18 16:41:23.423 +05:30 [Error] Connection id ""0HLFCJPFPP9FM"", Request id ""0HLFCJPFPP9FM:00000001"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<ValidateDeviceToken>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OnSolve.Mobile.Web.Filters.AuthorizeDeviceTokenAttribute.ValidateDeviceTokenAttribute.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-07-18 16:41:23.427 +05:30 [Information] Request finished in 3895.7884ms 500 
2018-07-18 16:42:17.018 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:43:28.550 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/  
2018-07-18 16:43:28.556 +05:30 [Information] Request starting HTTP/1.1 DEBUG http://localhost:55306/  0
2018-07-18 16:43:28.550 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/  
2018-07-18 16:43:28.647 +05:30 [Information] Request finished in 155.2577ms 200 
2018-07-18 16:43:28.686 +05:30 [Information] Request finished in 178.8896ms 200 text/html
2018-07-18 16:43:28.731 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui.css  
2018-07-18 16:43:28.735 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-standalone-preset.js  
2018-07-18 16:43:28.762 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/swagger-ui-bundle.js  
2018-07-18 16:43:28.847 +05:30 [Information] The file "/swagger-ui.css" was not modified
2018-07-18 16:43:28.848 +05:30 [Information] The file "/swagger-ui-standalone-preset.js" was not modified
2018-07-18 16:43:28.850 +05:30 [Information] The file "/swagger-ui-bundle.js" was not modified
2018-07-18 16:43:28.876 +05:30 [Information] Request finished in 151.7909ms 304 application/javascript
2018-07-18 16:43:28.883 +05:30 [Information] Request finished in 161.0193ms 304 text/css
2018-07-18 16:43:28.887 +05:30 [Information] Request finished in 151.2724ms 304 application/javascript
2018-07-18 16:43:29.073 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/swagger/v1/swagger.json  
2018-07-18 16:43:29.217 +05:30 [Information] Request finished in 733.0256ms 404 
2018-07-18 16:43:29.320 +05:30 [Information] Request finished in 247.4264ms 200 application/json
2018-07-18 16:43:42.748 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:55306/api/textmessage?messageId=1  
2018-07-18 16:43:42.869 +05:30 [Information] Authorization failed for user: null.
2018-07-18 16:43:42.875 +05:30 [Information] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'.
2018-07-18 16:43:42.883 +05:30 [Information] Executing ChallengeResult with authentication schemes ([]).
2018-07-18 16:43:42.895 +05:30 [Information] AuthenticationScheme: "Bearer" was challenged.
2018-07-18 16:43:42.902 +05:30 [Information] Executed action "OnSolve.Mobile.Web.Controllers.TextMessageController.Get (OnSolve.Mobile.Web)" in 53.7179ms
2018-07-18 16:43:42.905 +05:30 [Information] Request finished in 156.8995ms 401 
